# Generated by Django 3.2.2 on 2021-05-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_auto_20210516_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='manufacturer',
        ),
    ]
