# Generated by Django 3.2.2 on 2021-06-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_alter_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=70)),
                ('public', models.BooleanField()),
                ('mobile', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now=True)),
                ('hosp_img', models.ImageField(upload_to='static\\images\\hosp')),
                ('tot_iso_bed', models.SmallIntegerField()),
                ('iso_bed', models.SmallIntegerField()),
                ('tot_oxy_bed', models.SmallIntegerField()),
                ('oxy_bed', models.SmallIntegerField()),
                ('tot_icu_bed', models.SmallIntegerField()),
                ('icu_bed', models.SmallIntegerField()),
            ],
        ),
    ]
