# Generated by Django 3.2.2 on 2021-06-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0005_centers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Centers',
            new_name='Center',
        ),
        migrations.RenameField(
            model_name='center',
            old_name='hosp_img',
            new_name='hospital_image',
        ),
        migrations.RenameField(
            model_name='center',
            old_name='tot_icu_bed',
            new_name='total_icu_bed',
        ),
        migrations.RenameField(
            model_name='center',
            old_name='tot_iso_bed',
            new_name='total_iso_bed',
        ),
        migrations.RenameField(
            model_name='center',
            old_name='tot_oxy_bed',
            new_name='total_oxy_bed',
        ),
    ]
