# Generated by Django 3.2.2 on 2021-07-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0006_auto_20210618_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.CharField(default='www.amazon.com', max_length=50),
        ),
    ]
